services:
  team-builder:
    container_name: team-builder
    image: team-builder
    # build:
    #   context: ../
    #   dockerfile: Dockerfile
    volumes:
      - ./container/meta/:/app/meta
    networks:
      - docker-nginx-network
    restart: always

networks:
  docker-nginx-network:
    external: true